In [1]:
import pandas as pd

In [2]:
df_eklektores2024 = pd.read_excel('../../files/mitroa/professors_tables/professors_export_20241211.xlsx', sheet_name='Professors')
df_eklektores2024.head()

,Κωδικός Χρήστη,Όνομα,Επώνυμο,Φορέας,Σχολή,Τμήμα/Ινστιτούτο,Βαθμίδα,URL Βιογραφικού,Γνωστικό Αντικείμενο,ΦΕΚ Διορισμού,Σε αναστολή,Κατηγορία Χρήστη,"Παρ. 1, Άρ. 145, Ν. 4957/2022"
0,4200,IGNACIO,'-,University Complutense of Madrid,NaN,NaN,Καθηγητής,NaN,ANAESTHESIOLOGY\nLABORATORY ANIMALS,NaN,ΟΧΙ,Καθηγητής Αλλοδαπής,ΟΧΙ
1,1869,ANDRE AARNINK,AARNINK,Wageningen UR,NaN,NaN,Κύριος Ερευνητής,NaN,LIVESTOCK ENVIRONMENT,NaN,ΟΧΙ,Ερευνητής Αλλοδαπής,ΟΧΙ
2,5299,LEON,AARONS,The University of Manchester,NaN,NaN,Καθηγητής,NaN,PHARMACY,NaN,ΟΧΙ,Καθηγητής Αλλοδαπής,ΟΧΙ
3,4738,ERNEST,ABADAL,University of Barcelona,NaN,NaN,Καθηγητής,http://bd.ub.edu/pub/abadal,LIBRARY AND INFORMATION SCIENCE,NaN,ΟΧΙ,Καθηγητής Αλλοδαπής,ΟΧΙ
4,10536,GREGORY,ABADIAS,Institut Pprime,NaN,NaN,Καθηγητής,NaN,"MATERIALS SCIENCE,\nCONDENSED MATTER PHYSICS",NaN,ΟΧΙ,Καθηγητής Αλλοδαπής,ΟΧΙ

In [3]:
df_eklektores2025 = pd.read_excel('../../files/mitroa/professors_tables/professors_export_20251014.xlsx', sheet_name='Professors')
df_eklektores2025.head()

,Κωδικός Χρήστη,Όνομα,Επώνυμο,Φορέας,Σχολή,Τμήμα/Ινστιτούτο,Βαθμίδα,URL Βιογραφικού,Γνωστικό Αντικείμενο,ΦΕΚ Διορισμού,Σε αναστολή,Κατηγορία Χρήστη,"Παρ. 1, Άρ. 145, Ν. 4957/2022",Άδεια,Έναρξη άδειας,Λήξη άδειας
0,4200,IGNACIO,'-,University Complutense of Madrid,NaN,NaN,Καθηγητής,NaN,ANAESTHESIOLOGY\nLABORATORY ANIMALS,NaN,ΟΧΙ,Καθηγητής Αλλοδαπής,ΟΧΙ,NaN,NaN,NaN
1,1869,ANDRE AARNINK,AARNINK,Wageningen UR,NaN,NaN,Κύριος Ερευνητής,NaN,LIVESTOCK ENVIRONMENT,NaN,ΟΧΙ,Ερευνητής Αλλοδαπής,ΟΧΙ,NaN,NaN,NaN
2,5299,LEON,AARONS,The University of Manchester,NaN,NaN,Καθηγητής,NaN,PHARMACY,NaN,ΟΧΙ,Καθηγητής Αλλοδαπής,ΟΧΙ,NaN,NaN,NaN
3,4738,ERNEST,ABADAL,University of Barcelona,NaN,NaN,Καθηγητής,http://bd.ub.edu/pub/abadal,LIBRARY AND INFORMATION SCIENCE,NaN,ΟΧΙ,Καθηγητής Αλλοδαπής,ΟΧΙ,NaN,NaN,NaN
4,10536,GREGORY,ABADIAS,Institut Pprime,NaN,NaN,Καθηγητής,NaN,"MATERIALS SCIENCE,\nCONDENSED MATTER PHYSICS",NaN,ΟΧΙ,Καθηγητής Αλλοδαπής,ΟΧΙ,NaN,NaN,NaN

In [4]:
df_eklektores2026 = pd.read_excel('../../files/mitroa/professors_tables/professors_export_20260904.xlsx', sheet_name='Professors')
df_eklektores2026.head()

,Κωδικός Χρήστη,Όνομα,Επώνυμο,Φορέας,Σχολή,Τμήμα/Ινστιτούτο,Βαθμίδα,URL Βιογραφικού,Γνωστικό Αντικείμενο,ΦΕΚ Διορισμού,Κατηγορία Χρήστη,Ενεργή άδεια/κώλυμα αποκλεισμού από μητρώα,Ενεργή άδεια/κώλυμα αποκλεισμού από εκλεκτορικά/επιτροπές
0,4200,IGNACIO,'-,University Complutense of Madrid,NaN,NaN,Καθηγητής,NaN,ANAESTHESIOLOGY\nLABORATORY ANIMALS,NaN,Καθηγητής Αλλοδαπής,ΟΧΙ,ΟΧΙ
1,1869,ANDRE AARNINK,AARNINK,Wageningen UR,NaN,NaN,Κύριος Ερευνητής,NaN,LIVESTOCK ENVIRONMENT,NaN,Ερευνητής Αλλοδαπής,ΟΧΙ,ΟΧΙ
2,5299,LEON,AARONS,The University of Manchester,NaN,NaN,Καθηγητής,NaN,PHARMACY,NaN,Καθηγητής Αλλοδαπής,ΟΧΙ,ΟΧΙ
3,4738,ERNEST,ABADAL,University of Barcelona,NaN,NaN,Καθηγητής,http://bd.ub.edu/pub/abadal,LIBRARY AND INFORMATION SCIENCE,NaN,Καθηγητής Αλλοδαπής,ΟΧΙ,ΟΧΙ
4,10536,GREGORY,ABADIAS,Institut Pprime,NaN,NaN,Καθηγητής,NaN,"MATERIALS SCIENCE,\nCONDENSED MATTER PHYSICS",NaN,Καθηγητής Αλλοδαπής,ΟΧΙ,ΟΧΙ

In [9]:
df_eklektores2024.to_feather('../../files/mitroa/professors_tables/professors_export_20241211.feather')
df_eklektores2025.to_feather('../../files/mitroa/professors_tables/professors_export_20251014.feather')
df_eklektores2026.to_feather('../../files/mitroa/professors_tables/professors_export_20260904.feather')

In [10]:
df_eklektores2025.to_parquet('../../files/mitroa/professors_tables/professors_export_20251014.parquet')
df_eklektores2024.to_parquet('../../files/mitroa/professors_tables/professors_export_20241211.parquet')
df_eklektores2026.to_parquet('../../files/mitroa/professors_tables/professors_export_20260904.parquet')

In [20]:
df_test = pd.read_feather('../../files/mitroa/professors_tables/professors_export_20260904.feather')

In [15]:
df_test

,Κωδικός Χρήστη,Όνομα,Επώνυμο,Φορέας,Σχολή,Τμήμα/Ινστιτούτο,Βαθμίδα,URL Βιογραφικού,Γνωστικό Αντικείμενο,ΦΕΚ Διορισμού,Σε αναστολή,Κατηγορία Χρήστη,"Παρ. 1, Άρ. 145, Ν. 4957/2022"
0,4200,IGNACIO,'-,University Complutense of Madrid,NaN,NaN,Καθηγητής,NaN,ANAESTHESIOLOGY\nLABORATORY ANIMALS,NaN,ΟΧΙ,Καθηγητής Αλλοδαπής,ΟΧΙ
1,1869,ANDRE AARNINK,AARNINK,Wageningen UR,NaN,NaN,Κύριος Ερευνητής,NaN,LIVESTOCK ENVIRONMENT,NaN,ΟΧΙ,Ερευνητής Αλλοδαπής,ΟΧΙ
2,5299,LEON,AARONS,The University of Manchester,NaN,NaN,Καθηγητής,NaN,PHARMACY,NaN,ΟΧΙ,Καθηγητής Αλλοδαπής,ΟΧΙ
3,4738,ERNEST,ABADAL,University of Barcelona,NaN,NaN,Καθηγητής,http://bd.ub.edu/pub/abadal,LIBRARY AND INFORMATION SCIENCE,NaN,ΟΧΙ,Καθηγητής Αλλοδαπής,ΟΧΙ
4,10536,GREGORY,ABADIAS,Institut Pprime,NaN,NaN,Καθηγητής,NaN,"MATERIALS SCIENCE,\nCONDENSED MATTER PHYSICS",NaN,ΟΧΙ,Καθηγητής Αλλοδαπής,ΟΧΙ
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18891,19317,ΒΕΜΟΥΝΤ,ΩΡΜΠΑΚΚΕ,ΑΡΙΣΤΟΤΕΛΕΙΟ ΠΑΝΕΠΙΣΤΗΜΙΟ ΘΕΣ/ΝΙΚΗΣ,ΟΙΚΟΝΟΜΙΚΩΝ ΚΑΙ ΠΟΛΙΤΙΚΩΝ ΕΠΙΣΤΗΜΩΝ,ΠΟΛΙΤΙΚΩΝ ΕΠΙΣΤΗΜΩΝ,Επίκουρος Καθηγητής,http://www.polsci.auth.gr/index.php?lang=el&rm...,ΠΟΛΙΤΙΚΗ ΣΤΑ ΣΥΓΧΡΟΝΑ ΒΑΛΚΑΝΙΑ,580/Γ/27-6-2016,ΟΧΙ,Καθηγητής Ημεδαπής,ΟΧΙ
18892,9355,КОСТАДИН,ГАНЕВ,"National institute of geophysics, geodesy and ...",NaN,NaN,Καθηγητής,NaN,ATMOSPHERIC PHYSICS,NaN,ΟΧΙ,Καθηγητής Αλλοδαπής,ΟΧΙ
18893,3985,ГЕОРГИ,МАРИНОВ,"Medical University ""Profesor Paraskev Stoyanov...",NaN,NaN,Αναπληρωτής Καθηγητής,NaN,"ANATOMY, HISTOLOGY, EMBRYOLOGY.\nMAIN TOPICS:\...",NaN,ΟΧΙ,Καθηγητής Αλλοδαπής,ΟΧΙ
18894,7275,СРЂАН,ПЕТРОВИЋ,"Vinca Institute of Nuclear Sciences, Universit...",NaN,NaN,Κύριος Ερευνητής,NaN,CONDENSED MATTER PHYSICS WITH ION BEAMS,NaN,ΟΧΙ,Ερευνητής Αλλοδαπής,ΟΧΙ
18895,1568,БОРИС,СТРАУМАЛ,"Institute of Solid State Physics, Russian Acad...",NaN,NaN,Καθηγητής,http://www.issp.ac.ru/libm,MATERIALS SCIENCE,NaN,ΟΧΙ,Καθηγητής Αλλοδαπής,ΟΧΙ

In [21]:
df_test_parquet = pd.read_parquet('../../files/mitroa/professors_tables/professors_export_20260904.parquet')
df_test_parquet

,Κωδικός Χρήστη,Όνομα,Επώνυμο,Φορέας,Σχολή,Τμήμα/Ινστιτούτο,Βαθμίδα,URL Βιογραφικού,Γνωστικό Αντικείμενο,ΦΕΚ Διορισμού,Κατηγορία Χρήστη,Ενεργή άδεια/κώλυμα αποκλεισμού από μητρώα,Ενεργή άδεια/κώλυμα αποκλεισμού από εκλεκτορικά/επιτροπές
0,4200,IGNACIO,'-,University Complutense of Madrid,NaN,NaN,Καθηγητής,NaN,ANAESTHESIOLOGY\nLABORATORY ANIMALS,NaN,Καθηγητής Αλλοδαπής,ΟΧΙ,ΟΧΙ
1,1869,ANDRE AARNINK,AARNINK,Wageningen UR,NaN,NaN,Κύριος Ερευνητής,NaN,LIVESTOCK ENVIRONMENT,NaN,Ερευνητής Αλλοδαπής,ΟΧΙ,ΟΧΙ
2,5299,LEON,AARONS,The University of Manchester,NaN,NaN,Καθηγητής,NaN,PHARMACY,NaN,Καθηγητής Αλλοδαπής,ΟΧΙ,ΟΧΙ
3,4738,ERNEST,ABADAL,University of Barcelona,NaN,NaN,Καθηγητής,http://bd.ub.edu/pub/abadal,LIBRARY AND INFORMATION SCIENCE,NaN,Καθηγητής Αλλοδαπής,ΟΧΙ,ΟΧΙ
4,10536,GREGORY,ABADIAS,Institut Pprime,NaN,NaN,Καθηγητής,NaN,"MATERIALS SCIENCE,\nCONDENSED MATTER PHYSICS",NaN,Καθηγητής Αλλοδαπής,ΟΧΙ,ΟΧΙ
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20281,19317,ΒΕΜΟΥΝΤ,ΩΡΜΠΑΚΚΕ,ΑΡΙΣΤΟΤΕΛΕΙΟ ΠΑΝΕΠΙΣΤΗΜΙΟ ΘΕΣ/ΝΙΚΗΣ,ΚΟΙΝΩΝΙΚΩΝ ΚΑΙ ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ,ΠΟΛΙΤΙΚΩΝ ΕΠΙΣΤΗΜΩΝ,Επίκουρος Καθηγητής,http://www.polsci.auth.gr/index.php?lang=el&rm...,ΠΟΛΙΤΙΚΗ ΣΤΑ ΣΥΓΧΡΟΝΑ ΒΑΛΚΑΝΙΑ,580/Γ/27-6-2016,Καθηγητής Ημεδαπής,ΝΑΙ,ΝΑΙ
20282,9355,КОСТАДИН,ГАНЕВ,"National institute of geophysics, geodesy and ...",NaN,NaN,Καθηγητής,NaN,ATMOSPHERIC PHYSICS,NaN,Καθηγητής Αλλοδαπής,ΟΧΙ,ΟΧΙ
20283,3985,ГЕОРГИ,МАРИНОВ,"Medical University ""Profesor Paraskev Stoyanov...",NaN,NaN,Αναπληρωτής Καθηγητής,NaN,"ANATOMY, HISTOLOGY, EMBRYOLOGY.\nMAIN TOPICS:\...",NaN,Καθηγητής Αλλοδαπής,ΟΧΙ,ΟΧΙ
20284,7275,СРЂАН,ПЕТРОВИЋ,"Vinca Institute of Nuclear Sciences, Universit...",NaN,NaN,Κύριος Ερευνητής,NaN,CONDENSED MATTER PHYSICS WITH ION BEAMS,NaN,Ερευνητής Αλλοδαπής,ΟΧΙ,ΟΧΙ
20285,1568,БОРИС,СТРАУМАЛ,"Institute of Solid State Physics, Russian Acad...",NaN,NaN,Καθηγητής,http://www.issp.ac.ru/libm,MATERIALS SCIENCE,NaN,Καθηγητής Αλλοδαπής,ΟΧΙ,ΟΧΙ